steps:
  - name: golang:1.21
    entrypoint: /bin/bash
    args:
      - -c
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=$PROJECT_ID:asia-east1:main-db=tcp:$$API_DB_PORT &

        go install github.com/pressly/goose/v3/cmd/goose@v3.7.0
        goose -dir ./build/db/migration mysql "$$API_DB_USER:$$API_DB_PASS@tcp(127.0.0.1:$$API_DB_PORT)/$$API_DB_NAME" up
    secretEnv:
      [
        "API_DB_USER",
        "API_DB_PASS",
        "API_DB_HOST",
        "API_DB_PORT",
        "API_DB_NAME",
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/api-service:latest",
        "--target",
        "runner",
        "-f",
        "build/docker/go/Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/api-service:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "api-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/api-service:latest"
      - "--region"
      - "asia-east1"
      - "--add-cloudsql-instances=$PROJECT_ID:asia-east1:main-db"
      - "--update-secrets=
        API_APP_DOMAIN=API_APP_DOMAIN:latest,
        API_ENV=API_ENV:latest,
        API_PORT=API_PORT:latest,
        API_FRONT_URL=API_FRONT_URL:latest,
        API_DB_USER=API_DB_USER:latest,
        API_DB_PASS=API_DB_PASS:latest,
        API_DB_HOST=API_DB_HOST:latest,
        API_DB_PORT=API_DB_PORT:latest,
        API_DB_NAME=API_DB_NAME:latest,
        API_ENCRYPT_KEY=API_ENCRYPT_KEY:latest,
        API_JWT_SECRET=API_JWT_SECRET:latest,
        API_SENTRY_DSN=API_SENTRY_DSN:latest,
        INSTANCE_UNIX_SOCKET=INSTANCE_UNIX_SOCKET:latest"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/API_DB_HOST/versions/latest
      env: "API_DB_HOST"
    - versionName: projects/$PROJECT_ID/secrets/API_DB_NAME/versions/latest
      env: "API_DB_NAME"
    - versionName: projects/$PROJECT_ID/secrets/API_DB_USER/versions/latest
      env: "API_DB_USER"
    - versionName: projects/$PROJECT_ID/secrets/API_DB_PASS/versions/latest
      env: "API_DB_PASS"
    - versionName: projects/$PROJECT_ID/secrets/API_DB_PORT/versions/latest
      env: "API_DB_PORT"
