version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      target: runner
      dockerfile: ./build/docker/go/Dockerfile
    tty: true
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      bbs_network:
        ipv4_address: 172.30.0.2

  mysql:
    container_name: mysql
    build: ./build/docker/mysql/
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./build/docker/mysql/init:/docker-entrypoint-initdb.d
      - ./build/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./build/db/log:/var/log/mysql
      # 永続化するときにマウントするdir
      # - ./build/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${API_DB_PASS}
    ports:
      - ${API_DB_PORT}:3306
    networks:
      bbs_network:
        ipv4_address: 172.30.0.3

networks:
  bbs_network:
    external: true
